#!/usr/bin/env node
/* =============================================================================
 * BUSINESS SPACE INDEX GENERATOR
 * -----------------------------------------------------------------------------
 * Regenerates business/INDEX.md — one line per D#/H#/E#/Q# entry with status
 * and domain tags, so humans and agents can navigate the ledgers without
 * reading them whole. The workspace linter fails if INDEX.md is stale.
 *
 * Usage:  node scripts/build-index.js [repo-root]     (default: cwd)
 * Shared between tf-dashboard and tpc-dashboard.
 * ========================================================================== */

'use strict';
const fs = require('fs');
const path = require('path');

const FILES = [
  ['D', 'DECISIONS.md', 'Decisions'],
  ['H', 'HYPOTHESES.md', 'Hypotheses'],
  ['E', 'EXPERIMENTS.md', 'Experiments'],
  ['Q', 'OPEN_QUESTIONS.md', 'Open questions'],
];

function parseEntries(text) {
  const entries = [];
  const lines = text.split('\n');
  let cur = null;
  const flush = (end) => {
    if (!cur) return;
    cur.body = lines.slice(cur.start + 1, end).join('\n');
    entries.push(cur);
    cur = null;
  };
  lines.forEach((line, i) => {
    const m = line.match(/^###\s+([DHEQ]\d+)\s*[—–-]\s*(.*)$/);
    if (m) {
      flush(i);
      cur = { id: m[1], num: Number(m[1].slice(1)), title: m[2].trim(), start: i };
    }
  });
  flush(lines.length);
  return entries;
}

function statusOf(entry) {
  const m = entry.body.match(/^-\s*Status:\s*(.+)$/m);
  if (m) {
    const raw = m[1].replace(/\*/g, '').trim();
    const tok = raw.match(/^[A-Z][A-Z-]+/);
    return tok ? tok[0] : raw.split(/[\s(]/)[0];
  }
  // Q entries have no Status line
  return /\bRESOLVED\b/i.test(entry.body) ? 'RESOLVED' : 'OPEN';
}

function domainOf(entry) {
  const m = entry.body.match(/^-\s*Domain:\s*(.+)$/m);
  return m ? m[1].trim() : '?';
}

function buildIndex(root) {
  const biz = path.join(root, 'business');
  let out = '# Business Space index\n\n';
  out += '<!-- AUTO-GENERATED by scripts/build-index.js — DO NOT EDIT BY HAND.\n';
  out += '     Re-run `node scripts/build-index.js` after editing business/*.md;\n';
  out += '     the workspace linter fails when this file is stale. -->\n';
  for (const [prefix, fname, title] of FILES) {
    const fpath = path.join(biz, fname);
    if (!fs.existsSync(fpath)) continue;
    const entries = parseEntries(fs.readFileSync(fpath, 'utf8'))
      .filter((e) => e.id[0] === prefix)
      .sort((a, b) => a.num - b.num);
    out += `\n## ${title} (${prefix}#) — [${fname}](${fname})\n\n`;
    for (const e of entries) {
      out += `- **${e.id}** · ${statusOf(e)} · [${domainOf(e)}] — ${e.title}\n`;
    }
  }
  return out;
}

module.exports = { buildIndex };

if (require.main === module) {
  const root = path.resolve(process.argv[2] || process.cwd());
  const target = path.join(root, 'business', 'INDEX.md');
  fs.writeFileSync(target, buildIndex(root));
  console.log('wrote ' + target);
}
